### ISSUE TITLE
[H02] 3.1.4 감귤마켓 피드 Home with posts

### ISSUE THREAD

**Issue by zeroyouth** [nurimeansworld/strawberry_market#15]
## 페이지 설명
- 감귤마켓 피드는 사용자들이 올린 **게시글**들이 표시되는 페이지입니다.
- 감귤마켓 피드에는 자신이 **팔로우**한 사용자의 게시글만 확인할 수 있습니다.

## 리스트
- ~~html 작업 완료~~
- css 작업
  - [x] 하트,채팅 버튼에 class `on` 속성주기 : **3.1.15 좋아요 버튼**
   - (빈 하트를 클릭하면 색이 칠해진 하트로 변하고, 색이 칠해진 하트를 누르면 빈 하트로 변합니다.)

- **js 작업**
  - [x] 감귤마켓 상단 nav 클릭시 search 페이지 `S01.html`로 넘어가도록 하기 
  #30 
  - [x] 게시글 home-post 클릭시 `P01.html` 페이지로 넘어가도록 하기 
  - [x] 댓글 부분 누르면 Post페이지 `U01.html`로 넘어가도록 하기 
  - [x] 하트 버튼 누르면 class `on` 속성 부여

## CHECK::
- ~~A01 프로필 수정사항 필요한 거 묻고,  2차 수정해야 할 것 같음.~~(완료)
- ~~하트버튼, 채팅버튼에 css position을 변경해야 할 듯~~(완료)

**Comment by nurimeansworld** [comment]
![image](https://user-images.githubusercontent.com/69141304/151696779-0af47193-117a-4111-8c48-22f5423f21f6.png)
@zeroyouth 영은님! 제 페이지 작업하다가 공유드릴 부분 있어서 코멘트 남겨요~
1. 프로필 이미지, 게시글 이미지 border-radius 처리랑
2. 게시글 영역이 390px로 해도 조금 벗어납니다..!

이렇게 2가지 확인 부탁드려요! 감사합니다 🙏

**Comment by zeroto99** [comment]
@zeroyouth 영은님! 
모듈 작업하신 내용 중에 user-name 부분 피그마 보시면 폰트 사이즈 14px입니다. 
지금은 h4로만 마크업됐고 따로 css가 없어서 폰트 사이즈 추가 부탁드려요~
![image](https://user-images.githubusercontent.com/89337955/152355723-f95fda1c-8356-42df-b16e-447171e7273b.png)

**Comment by zeroyouth** [comment]
![수정](https://user-images.githubusercontent.com/86909942/152360758-f6501d59-f8e6-421e-a2e2-9eb384a0734b.JPG)

@nurimeansworld @zeroto99 
[A01] 변경된 부분 공유합니다.
- user-name 폰트 사이즈 추가
- 아이콘 크기 지정
- width값 없애고 메뉴 버튼 위치 변경했습니다.
