### ISSUE TITLE
[S01] 3.1.5 검색 

### ISSUE THREAD

**Issue by ndnv819** [nurimeansworld/strawberry_market#24]
### 내용

필수 과제
- 감귤마켓 피드 상단에 돋보기 버튼(검색 버튼)을 클릭하면 표시되는 페이지입니다.
- 사용자 이름을 검색할 수 있는 페이지입니다.
- 검색 기능은 구현하지 않습니다.

선택(도전) 과제
- 감귤마켓 피드 상단에 돋보기 버튼(검색 버튼)을 클릭하면 표시되는 페이지입니다.
- 사용자 이름과 계정을 검색할 수 있는 페이지입니다. 입력창에 텍스트를 입력하면 해당하는 사용자가 나오도록 합니다.
- 검색어와 같은 단어에는 주황색 글씨가 표시됩니다.

### 진행 상황
- [x] html
- [x] css
- [x] javascript
- [x] api (선택 과제)

### CHECK
`검색어와 같은 단어 하이라이트 미구현`

**Comment by zeroto99** [comment]
선택(도전) 과제
- 감귤마켓 피드 상단에 돋보기 버튼(검색 버튼)을 클릭하면 표시되는 페이지입니다.
- 사용자 이름과 계정을 검색할 수 있는 페이지입니다. 입력창에 텍스트를 입력하면 해당하는 사용자가 나오도록 합니다.
- 검색어와 같은 단어에는 주황색 글씨가 표시됩니다.

**Comment by zeroto99** [comment]
- [ ] input 할 때마다 동일한 검색 결과 연속 출력 

![검색 페이지 오류](https://user-images.githubusercontent.com/89337955/151969716-c6e074a8-f0d3-4cd9-80f4-6bef0d003dd3.gif)
