### ISSUE TITLE
[A02, L03] 누리 담당 컴포넌트 변경사항 반영

### ISSUE THREAD

**Issue by nurimeansworld** [nurimeansworld/strawberry_market#30]
## [A02] nav 컴포넌트
- [x] 검색 실제 페이지로 반영

## [L03] 회원 정보 등록
** P04 내 프로필 페이지 작업하며 수정이 필요한 부분 주석처리하여 추가
- [x] js - 이미지 등록
- [x] js -  입력 값 error-message

**Comment by nurimeansworld** [comment]
@zeroyouth @greenknight03 
영은님, 희정님 제 담당 컴포넌트부분 링크가 바뀌었는데 제가 임의로 커밋하기엔 충돌날까봐 코멘트로 공유드립니다.
각각의 코드를 아래 코드로 수정 부탁드려요! (아래 링크를 클릭하면 표시된 곳으로 이동합니다.)
```html
 <a href="./S01.html" class="link-search">
  <img src="../assets/icon/icon-search.png" alt="검색 페이지로 이동">
</a>
```
## 영은님 작업 파일
- [A01.html line 16~19](https://github.com/zeroyouth/strawberry_market/blob/2bf4f23065206c483d2056345159e8d721153f50/html/A01.html#L16-L19)
- [H01.html line 15~18](https://github.com/zeroyouth/strawberry_market/blob/2bf4f23065206c483d2056345159e8d721153f50/html/H01.html#L15-L18)
- [H02.html line 15~18](https://github.com/zeroyouth/strawberry_market/blob/2bf4f23065206c483d2056345159e8d721153f50/html/H02.html#L15-L18)

## 희정님 작업 파일
- [BTM.html linee 17~20](https://github.com/nurimeansworld/strawberry_market/blob/8843699febe1f7402082871a4c12aee99976115a/html/BTM01.html#L17-L20)

**Comment by nurimeansworld** [comment]
해당 이슈 완료하여 close 합니다 🙏

**Comment by zeroyouth** [comment]
우와 변경할 라인까지 찾아주시다뇨ㅠㅠ 섬세하세여~
확인하고 변경했습니다. 감사해요!👍
