### ISSUE TITLE
3.1.14 하단 탭 메뉴

### ISSUE THREAD

**Issue by greenknight03** [nurimeansworld/strawberry_market#36]
### **요구사항**

- 하단 탭 메뉴는 홈, 채팅, 게시물 작성, 프로필 4개의 메뉴로 구성되어 있습니다.
- 모든 페이지는 페이지 경로에 해당하는 탭 메뉴가 활성화됩니다.

### **완료**

- 하단 메뉴 버튼 페이지 이동 활성화 완성 
-  각 페이지마다 메뉴 버튼 색 활성화 시키려면 li class에 on 적용하기

**Comment by nurimeansworld** [comment]
작업 완료하여 close 합니다 🙏
