### ISSUE TITLE
이미지 등록용 이슈

### ISSUE THREAD

**Issue by nurimeansworld** [nurimeansworld/strawberry_market#4]

**Comment by nurimeansworld** [comment]
<img width="592" alt="market_1" src="https://user-images.githubusercontent.com/69141304/147580275-0b5f20e0-7c84-4895-92ca-89271ee1f184.png">
![Uploading market_2.png…]()

**Comment by nurimeansworld** [comment]
![image](https://user-images.githubusercontent.com/69141304/147941661-67a2ac1d-07b0-4ad6-8cfd-2a39003d7e6e.png)

**Comment by nurimeansworld** [comment]
![image](https://user-images.githubusercontent.com/69141304/153535829-d60fd615-291c-49a2-a52b-86f05893d804.png)

**Comment by zeroyouth** [comment]
1. index.html intro.html(스플래시, 넘어가는 것) 0  
![1](https://user-images.githubusercontent.com/86909942/153747250-a53aa4ed-adb5-4c5a-b221-f2180a3df989.gif)

2. login.html (유효성 검사도 보여주면 좋을 것 같아요!) 0
![2](https://user-images.githubusercontent.com/86909942/153747252-4b0d9bf6-8c27-48b9-9f3f-81159c0e705b.gif)

3. join.html (화면 2개 넘어가는 것) 0
![3](https://user-images.githubusercontent.com/86909942/153747257-68b2bcbd-0cfb-48a5-904a-25fefee22748.gif)


홈
4. home.html, followfeed.html (로그인 후 팔로잉 하나도 없는 상태, 로그인 후 팔로잉 있어서 게시글 뜨는 상태)  0
![4](https://user-images.githubusercontent.com/86909942/153747260-e9b4b788-bc6e-4087-8706-362267577f3f.gif)
검색
5. searh.html (상단 돋보기, 검색하기 누르면 검색 페이지로 이동 -> 검색한 내용 나오는 것) 0
![5](https://user-images.githubusercontent.com/86909942/153747286-e7491424-b150-4ff9-a23a-a1136d7ab0cc.gif)

채팅
6. chat.html, chatlist.html (채팅 리스트에서 채팅 창으로 넘어가는 것) 0
![6](https://user-images.githubusercontent.com/86909942/153747299-3ad2f035-811c-4d6c-8729-44eec3a28af7.gif)

게시물 작성
7. post.html (게시글 작성 후 업로드 클릭하여 게시글 등록 확인) 0
![7](https://user-images.githubusercontent.com/86909942/153747294-d2221590-7045-477b-992c-595c20f7d645.gif)

게시물 상세
8. postdetail.html (댓글 아이콘 눌러 상세 페이지로 이동. 댓글 작성하여 추가된 것 확인) 0
아직 미완 - postedit.html 게시글 수정 누르면 이동.
![8](https://user-images.githubusercontent.com/86909942/153747313-ef897173-eae7-407a-b91b-b5f4580ce135.gif)

게시글 수정 or 신고
9. postdetail.html (모달 메뉴 클릭하여 게시글 수정 or 신고 모달 뜨게. 기능도 되면 그것도 확인) x
댓글 수정 or 신고
10. postdetail.html (모달 메뉴 클릭하여 댓글 신고 모달 뜨게. 신고 눌러서 되는 것 확인) x

마이 프로필
11. myprofile.html (단순 스크롤 천천히 내렸다 올라오기. 판매 상품 스크롤 해보고, 게시글의 경우 앨범으로 보기도 클릭해보기) 0
![11](https://user-images.githubusercontent.com/86909942/153747320-3f079fc2-2320-4700-a176-5825c0bfdc55.gif)

유저 프로필
12. profile.html (단순 스크롤 천천히 내렸다 올라오기. 팔로우 버튼 눌렀다 변하는 것 확인, 판매 상품 스크롤 해보고, 게시글의 경우 앨범으로 보기도 클릭해보기) 0
![12](https://user-images.githubusercontent.com/86909942/153747325-3c89fa25-e70e-460b-9daf-26e625650805.gif)

팔로워
13. followers.html (버튼 클릭하여 팔로우 on/off 보여주기. 상대방 프로필로 이동하는 것도 보여주기)
팔로잉 0
![13](https://user-images.githubusercontent.com/86909942/153747331-d4d9375b-581f-4c0f-ba7a-deabf3554b04.gif)

14. followings.html (이건 팔로우를 10명 넘게 해서 목록이 스크롤 되는 것도 보이면 좋을 것 같아요!) 0
![14](https://user-images.githubusercontent.com/86909942/153747337-50aecd0d-89ba-4db2-bd3b-3bfec547e22a.gif)

**Comment by greenknight03** [comment]
15. myprofile.html (상단 메뉴 클릭 -> 로그아웃 클릭 -> 로그아웃)  
<img src="https://user-images.githubusercontent.com/92960723/153748344-9c31673b-fcc1-4747-b063-9f2ba1512159.gif">

16. accountedit.html (myprofile.html에서 내 프로필수정 누르고 -> 수정하여 저장까지) 좀 길다면 적당히 잘라주세요)
<img src="https://user-images.githubusercontent.com/92960723/153748386-364dff00-aef3-4fad-bc83-3255f1cb947e.gif">

17. product.html (myprofile.html에서 상품 등록 누르고 데이터 입력하여 저장버튼 활성화까지) 좀 길다면 적당히 잘라주세요)

**Comment by greenknight03** [comment]
마이 프로필 
로그아웃 
myprofile.html (상단 메뉴 클릭 -> 로그아웃 클릭 -> 로그아웃)  
![프로필로그아웃](https://user-images.githubusercontent.com/92960723/153748447-97dc681e-fda1-458e-98fb-f15080aff7a3.gif)

프로필 수정
![프로필수정](https://user-images.githubusercontent.com/92960723/153748465-7fb6c22a-7ec9-4ca0-96dc-83fbf8028d98.gif)

상품 등록
![상품등록](https://user-images.githubusercontent.com/92960723/153748485-118b6333-7daa-44a0-ab41-74b5117cab7a.gif)

상품 수정
![상품수정](https://user-images.githubusercontent.com/92960723/153748515-593f4d20-3522-4ed9-a898-f98a888c73a0.gif)

상품 삭제
![상품삭제](https://user-images.githubusercontent.com/92960723/153748525-8686cd58-e904-4fee-8525-576af9a60b32.gif)

상품 사이트로 이동
![상품사이트이동](https://user-images.githubusercontent.com/92960723/153748544-c4e968a8-fce7-4e56-ae70-1da32bdcfae7.gif)

**Comment by nurimeansworld** [comment]
![image](https://user-images.githubusercontent.com/69141304/153748670-ddfc60ae-7c66-416b-9a7d-9467f6b40a04.png)
우선 4번째 피드 채워진 이미지 빠진 상태로 추가

**Comment by zeroto99** [comment]
![UI](https://user-images.githubusercontent.com/89337955/153886628-c22c7e9e-1b7c-4a19-a29b-1bef0dc4d44e.jpg)

**Comment by zeroto99** [comment]
![join](https://user-images.githubusercontent.com/89337955/154136855-56d58586-e5d9-4053-bd60-1983d330905e.gif)

**Comment by zeroto99** [comment]
## 기능 GIF 
* 홈 - 피드 
![feed](https://user-images.githubusercontent.com/89337955/154808243-27f7d259-a6f8-4854-9988-42c8cf9e679c.gif)

**Comment by zeroto99** [comment]
## 기능 GIF 

* 내 프로필 - 등록 상품 - 웹사이트에서 보기 
![프로필 페이지 - 내 상품 - 웹사이트에서 보기](https://user-images.githubusercontent.com/89337955/155849036-8466debe-7267-454b-8f4b-4f74b1eac7be.gif)

**Comment by nurimeansworld** [comment]
리드미 작성까지 완료하여 close 합니다 🙏
