### ISSUE TITLE
[QA] 회원가입 - 프로필 설정 

### ISSUE THREAD

**Issue by zeroto99** [nurimeansworld/strawberry_market#71]
## 내용
- [x] 프로필 이미지 용량 초과 시에 아무 알림이 없습니다. 

![profile-limit 알림 없음 ](https://user-images.githubusercontent.com/89337955/154093049-3e20ef0b-219b-4a02-be6a-124b034ee89d.gif)

**Comment by nurimeansworld** [comment]
확인하였고 금주내로 수정하여 반영하겠습니다!

**Comment by nurimeansworld** [comment]
회원가입 페이지 포함 계정 정보 수정 페이지도 이미지 알럿이 없길래 같이 추가해두었습니다 🙏

**Comment by nurimeansworld** [comment]
작업 완료하여 close 합니다 🙏
