### ISSUE TITLE
[QA] 팔로우

### ISSUE THREAD

**Issue by zeroto99** [nurimeansworld/strawberry_market#72]
## 내용
- [ ] 유저 검색 - 유저 프로필 클릭 - 팔로우 → 팔로우 안됨 
- [ ] 팔로워의 팔로잉 목록 - 유저 팔로우 →  팔로우 안됨 
- [ ] 내 팔로워 목록 - 유저 팔로우 → 팔로잉 안됨
*참고 (두번째 gif에 유저 3명 팔로우 되있는 건 감귤마켓에서 팔로우해둔겁니다. )
![팔로우](https://user-images.githubusercontent.com/89337955/154115108-95824b07-d855-465a-bf54-7d4aa6f99de7.gif)
![팔로잉](https://user-images.githubusercontent.com/89337955/154116574-ef72987c-fd86-409d-a35c-caa270fb3a23.gif)

@nurimeansworld

**Comment by nurimeansworld** [comment]
지아님 팔로우 기능이 필수가 아닌 선택기능이었어서 기능 구현이 되어있지 않는게 맞긴 합니다..^_ㅜ

**Comment by zeroto99** [comment]
오우 선택형도 다 하신줄 알았어요 ㅎㅎ.. gif 생성 시에 작업하신 기능 다 담아드리고 싶어서 QA로 남겨뒀었는데 그럼 해당 부분은 버튼 활성화만 보여주는 걸로 하겠습니다!
