### ISSUE TITLE
[QA] 내 프로필 - 앨범형 

### ISSUE THREAD

**Issue by zeroto99** [nurimeansworld/strawberry_market#76]
## 내용
- [x] 앨범형이 화면에 렌더되지 않습니다. 컴포넌트 수정 후 반영한다는 주석은 확인했으나 일단 QA에 올리도록 하겠습니다.
![마이프로필-앨범형](https://user-images.githubusercontent.com/89337955/154144389-e44cc88c-23bf-4570-a6d6-48bc0cfe2df3.gif)

@nurimeansworld

**Comment by nurimeansworld** [comment]
이미지가 여러 개인 경우 url을 다 받아와서 표시되지 않았습니다.
이미지가 여러 개일 경우 1개의 이미지만 보여주고 여러 이미지라는 표시를 class로 구분주어 출력하였습니다.
다만 지금 이미지 높이가 들쭉날쭉이라 해당 부분 작업 이어서 진행 예정입니다 🙏 
<img width="434" alt="image" src="https://user-images.githubusercontent.com/69141304/154945852-c526416b-e6a4-4a5c-b98e-87836600424d.png">

**Comment by nurimeansworld** [comment]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/69141304/154963671-bf2547be-d0a7-4580-87ff-ab54d68c8e63.png">
기존에 설정된 이미지 width 값에 맞게 height 값 변경에 어려움이 있어서 이미지를 피그마 사이즈대로 고정시키고 가운데 정렬로하여 이미지 크기는 반응형을 포기(?).. 하고 레이아웃 쪽으로 수정하였습니다...흑..

**Comment by nurimeansworld** [comment]
작업 완료하여 close 합니다 🙏
