### ISSUE TITLE
[QA] 홈 피드 리렌더링 

### ISSUE THREAD

**Issue by zeroto99** [nurimeansworld/strawberry_market#94]
## 내용 
* 홈에서 팔로워의 프로필 클릭 후에 하단의 홈을 클릭하면 피드가 제대로 렌더링되지 않습니다. 팔로워가 없는 경우의 화면이 나옵니다. 
![홈 - 리렌더링 에러](https://user-images.githubusercontent.com/89337955/155851886-a2aaa031-b023-434c-95e0-49c415e50990.gif)

**Comment by zeroyouth** [comment]
넵!! 확인하고 수정해서 push 해두었습니다.
![수정사항](https://user-images.githubusercontent.com/86909942/155873513-19644986-c1ef-4faf-8db4-be48867b772f.gif)
